class YoutubeChaptersGetter {
	private readonly youtube: string
	constructor(youtube = 'https://youtube.com') {
		this.youtube = youtube
	}

	private async getVideo(videoId: string) {
		try {
			const response = await fetch(`${this.youtube}/watch?v=${videoId}`)
			return await response.text()
		} catch (error) {
			console.error('getVideo err: ', error)
		}
	}

	private getScript(html: string) {
		try {
			const scriptTagStart = 'var ytInitialData = '
			const scriptTagEnd = '</script>'

			const startIndex = html.indexOf(scriptTagStart)
			if (startIndex === -1) return null

			const endIndex = html.indexOf(scriptTagEnd, startIndex)
			if (endIndex === -1) return null

			const ytInitialDataString = html
				.slice(startIndex + scriptTagStart.length, endIndex)
				.trim()
			if (ytInitialDataString.endsWith(';')) {
				return ytInitialDataString.slice(0, -1)
			}

			return ytInitialDataString
		} catch (error) {
			console.error('getScript err: ', error)
		}
	}

	async getChapter(videoId: string) {
		try {
			const ytInitialDataJson = await JSON.parse(
				this.getScript(await this.getVideo(videoId))
			)
			const chapterData =
				ytInitialDataJson['engagementPanels'][1][
					'engagementPanelSectionListRenderer'
				]['content']['macroMarkersListRenderer']['contents']
			const areAutoGenerated =
				'macroMarkersInfoItemRenderer' in chapterData[0]
			const filteredContents = chapterData.slice(areAutoGenerated ? 1 : 0)

			const chapters: {
				title: string
				time: string
				url: string
			}[] = filteredContents.map(chapterItem => {
				const chapter = chapterItem.macroMarkersListItemRenderer
				const timeStr = chapter.timeDescription.simpleText
				const url =
					this.youtube +
					chapter.onTap.commandMetadata.webCommandMetadata.url

				return {
					title: chapter.title.simpleText,
					time: timeStr,
					url,
				}
			})
			return chapters
		} catch (error) {
			console.error('getChapter err: ', error)
			return []
		}
	}
}

export default new YoutubeChaptersGetter()
